#data_root: data
# raw_dir: data/raw
# processed_dir: data/processed
# batch_size: 32
# epochs: 50
# learning_rate: 1e-3
data_root: "C:/Users/acer/OneDrive/Desktop/OCR/devangari-ocr/data"
batch_size: 8
num_channels: 1
hidden_size: 256
learning_rate: 0.0005
epochs: 30

# will be auto-calculated but put placeholder
num_classes: 200
