num_classes: 81
num_channels: 1
hidden_size: 256

img_height: 32
img_width: 256

batch_size: 64
epochs: 50
learning_rate: 0.001
weight_decay: 1e-5
scheduler_step: 15
scheduler_gamma: 0.5

train_samples: 5000
samples_per_word: 1
fonts_dir: "fonts"
output_dir: "data/word_images"
charset_path: "charset.txt"
